version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"  # Vite uses port 5173
    volumes:
      - .:/app  # Sync local files with the container for live updates
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fixes file change detection in Docker
    restart: always