version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"  # Map port 3000 on host to port 80 in container
    volumes:
      - .:/app  # Sync local files with the container (for development)
      - /app/node_modules  # Prevent overwriting node_modules
    restart: always